org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.java.installations.fromEnv=JAVA_HOME_17_X64,JAVA_HOME_21_X64,JAVA_HOME_25_X64

mod_id=waypointsplus
mod_name=Waypoints Plus
mod_version=1.0.7
mod_group_id=pl.slogerski.waypointsplus
mod_license=All Rights Reserved
mod_authors=Slogerski
mod_description=Client-side waypoint manager for Minecraft.
release_channel=release

minecraft_1_21_4=1.21.4
minecraft_range_1_21_4=>=1.21.2 <=1.21.4
yarn_1_21_4=1.21.4+build.8
fabric_api_1_21_4=0.119.4+1.21.4

minecraft_1_21_8=1.21.8
yarn_1_21_8=1.21.8+build.1
gson_version=2.11.0
fabric_api_1_21_8=0.136.1+1.21.8

minecraft_26_1_2=26.1.2
fabric_api_26_1_2=0.153.0+26.1.2
